version: '2.1'
orbs:
  terraform: circleci/terraform@3.0.0



jobs:
  terraformer-plan:
     executor: terraform/default
     path: env/${CIRCLE_BRANCH}
     steps:
       - checkout
       - terraform/init
       - terraform/plan

workflows:
  deploy_infrastructure:
    jobs:
      - terraformer-plan:
           context: "AWS Credentials"

