version: '2.1'
orbs:
  terraform: circleci/terraform@3.0.0



jobs:
  terraformer-plan: &terraformer-plan
    executor: terraform/default
    working_directory: ~/project
    parameters:
      tf-path:
        description: tf path
        type: string
    steps:
      - checkout
      - terraform/init:
           path: << parameters.tf-path >>
      - terraform/plan:
           path: << parameters.tf-path >>


           #terraformer-apply: &terraformer-apply
           #executor: terraform/default
           # working_directory: ~/project
           #parameters:
           #tf-path:
           #description: tf path
           #type: string
           # steps:
           #- checkout
           #- terraform/apply:
           #path:  << parameters.tf-path >>

  terraformer-plan-master: *terraformer-plan
  terraformer-plan-staging: *terraformer-plan
  terraformer-plan-develop: *terraformer-plan
#terraformer-apply-master: *terraformer-apply
#terraformer-apply-staging: *terraformer-apply
#terraformer-apply-develop: *terraformer-apply

workflows:
  deploy_infrastructure:
    jobs:
      - terraformer-plan-develop:
           context: "AWS Credentials"
           tf-path: ./environments/development
           filters:
             branches:
               only:
                  - main

      - terraformer-plan-stage:
           context: "AWS Credentials"
           tf-path: ./environments/staging
           filters:
             branches:
               only:
                  - staging

      - terraformer-plan-master:
            context: "AWS Credentials"
            tf-path: ./environments/production
            filters:     
              branches:
                only:
                   - master

      - hold-apply:
            type: approval
            filters:
              branches:
                only:
                   - master
                   - main
                   - staging
            requires:
                   - terraformer-plan-master
                   - terraformer-plan-stage
                   - terraformer-plan-develop
         
                     # - terraformer-apply-develop:
                     #  context: "AWS Credentials"
                     #checkout: true
                     #   requires:
                     #   - hold-apply

         

