version: '2.1'
orbs:
  terraform: circleci/terraform@3.0.0



jobs:
  terraformer-plan:
     executor: terraform/default
     steps:
       - checkout
       - terraform/init:
             path: 'environments/${CIRCLE_BRANCH}'
       - terraform/plan:
             path: environments/${CIRCLE_BRANCH}

workflows:
  deploy_infrastructure:
    jobs:
      - terraformer-plan:
           context: "AWS Credentials"

